version: '3'
services:

  wordpress:
    image: wordpress
    container_name: hakuba-matata_wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
       - ./themes/hakuba_matata:/var/www/html/wp-content/themes/hakuba_matata
       - ./uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_PASSWORD: my-secret-pw

  mysql:
    image: mysql:5.7
    container_name: hakuba-matata_mysql
    volumes:
      ##永続化＃＃
      - "./mysql/data:/var/lib/mysql"
      ##初期データ投入＃＃
      # - "./mysql/init:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw